feat: added loading spinner
CESNET/satosa-module-webauthn pull request #48
Opened 2021-08-24 21:29 UTC by xpavlic

When adding or removing a token on manage tokens page,
content is hidden, loading spinner is displayed and
continue button is disabled. Credential_loading function
checks every 5 seconds if the change already took effect
with 2 minutes loading timeout. 

Merging is possible after merge of #44 .

2021-08-30 11:07 UTC, melanger commented on app/static/js/satosa_webauthn.js
> +    }
If initially the logout button has exactly 1 of `disabled` or `active`:
```
logout_button.classList.toggle("disabled");
logout_button.classList.toggle("active");
```

2021-08-30 11:07 UTC, melanger commented on app/static/js/satosa_webauthn.js
>      }
If initally the `element` has exactly one of `d-none` or `d-block`:
```
element.classList.toggle("d-none");
element.classList.toggle("d-block");
```

2021-09-01 14:46 UTC, melanger approved these changes
@xpavlic Rebased on the current main and slightly changed to keep compatibility with MUNI framework.

It would be nice to hide a smaller portion of the UI, instead of hiding everything and just showing the spinner, but it works nicely.

2021-09-09 07:59 UTC, xpavlic commented
Register and delete tokens process now hide just connected conent, show loading spinner instead and disable register, delete and continue buttons.

2021-09-09 12:45 UTC, melanger requested changes

2021-09-09 12:45 UTC, melanger commented on app/templates/credentials.html
> +            <span class="visually-hidden">Loading...</span>
change `Loading...` to `{{ _('Loading…') }}` (i18n + ellipsis character) and add a translation

2021-09-09 12:45 UTC, melanger commented on app/templates/credentials.html
> +            </div>
include the same spinner as in `app/templates/credentials.html`

2021-09-09 12:46 UTC, melanger commented
Please add translations for all text that is shown to user (everything except log messages)

2021-09-15 07:13 UTC, xpavlic commented on app/templates/credentials.html
> +            </div>
I am not sure what do you mean. Both spinners in `app/templates/credentials.html` are same.

2021-09-15 07:16 UTC, melanger commented on app/templates/credentials.html
> +            </div>
That is the problem, the same source code is copied in two places. Please move it to a single file which is included in two locations.

2021-09-15 20:29 UTC, melanger commented on app/templates/credentials.html
> +                        <span>{{ _('Turn off WebAuthn authentication') }}</span>
this seems like a typo

2021-09-16 08:11 UTC, melanger approved these changes

2021-09-16 08:12 UTC, merged