feat: new script to sign mfa tokens in Perun
CESNET/satosa-module-webauthn pull request #52
Opened 2021-09-09 11:31 UTC by xpavlic

added new directory 'scripts' added README.md with informations about scripts and added bash script
unsignedMfaTokensToSigned, which convert unsigned mfa tokens to signed in Perun

2021-09-09 12:39 UTC, melanger requested changes

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +    return user, password, signing_jwk, oidc_jwk, signing_alg, oidc_alg, client_secret, signing_kid, oidc_kid
you can use [argparse](https://docs.python.org/3/howto/argparse.html) to reduce boilerplate code

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +                                                                    'iss': 'https://oidc.muni.cz/oidc/',
add a configuration option, the default can be `'https://oidc.muni.cz/oidc/'`

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +                                                                    'acr': 'https://refeds.org/profile/mfa'})
add a configuration option, with default 'https://refeds.org/profile/mfa'`

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +    url = 'https://id.muni.cz/mfaapi/token'
add a configuration option, the default can be `'https://id.muni.cz/mfaapi/token'`

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +    rpc_url = "https://idm.ics.muni.cz/ba/rpc/json/"
add a configuration option, the default can be `"https://idm.ics.muni.cz/ba/rpc/json/"`

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +    rpc_users_url = rpc_url + "usersManager/getUsersByAttributeValue?attributeName=urn:perun:user:attribute-def:def:mfaTokens:mu&attributeValue=%"
add a configuration option with default `"urn:perun:user:attribute-def:def:mfaTokens:mu"`

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +                                                                                              "id"]) + "&attrNames[]=urn:perun:user:attribute-def:def:login-namespace:mu&attrNames[]=urn:perun:user:att
add a configuration option with default `"urn:perun:user:attribute-def:def:login-namespace:mu"`

2021-09-09 12:39 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +        eppn = uco + "@muni.cz"
only add `"@muni.cz"` if there is no `@` in `data[0]["value"]`

2021-09-09 12:39 UTC, melanger commented on scripts/README.md
> +- `-c/--clientSecret <string> `    oidc client secret
You can just mention `./unsignedMfaTokensToSigned.py --help` which prints all the arguments

2021-09-15 08:41 UTC, melanger requested changes

2021-09-15 08:41 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +                             "default=urn:perun:user:attribute-def:def:login-namespace:mu")
syntax error, `default="` instead of `"default=`, missing comma after the `help` argument

2021-09-15 08:55 UTC, xpavlic commented on scripts/unsignedMfaToknesToSigned.py
> +                             "default=urn:perun:user:attribute-def:def:login-namespace:mu")
It is just string divided into two lines. Both lines are part of `help` value. `default` value is defined on the previous line.

2021-09-15 10:23 UTC, melanger commented on scripts/unsignedMfaToknesToSigned.py
> +                             "default=urn:perun:user:attribute-def:def:login-namespace:mu")
OK, then you should use `ArgumentDefaultsHelpFormatter` which includes the default in the help text automatically without the need to copy it there

2021-09-16 00:31 UTC, melanger approved these changes

2021-09-16 00:31 UTC, merged